services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Dev\Foundry\App\Factory\:
        resource: '../src/Factory'

    # Example test cases
    Dev\Foundry\App\Example\Cache\Factory\ExampleFactory: ~
    Dev\Foundry\App\Example\Cache\Adapter\Repository\ExampleCacheRepository: ~
